### ISSUE TITLE
Environment lookup stops whenever it encounters a Git repo inside subdir of home

### ISSUE THREAD

**Issue by vdayanand** [StefanKarpinski/Pkg3.jl#8]
Due to this, I am unable to load any added packages

**Comment by StefanKarpinski** [comment]
This is by design. Can you describe your circumstance in a bit more detail?

**Comment by vdayanand** [comment]
My Julia bin was in /home/osboxes/juliapro/JuliaPro/Julia. /home/osboxes/juliapro is a Git directory. I suppose this is a weird setup.
